SistemaDocumentoNetCore/Models/Documento.cs
using System.ComponentModel.DataAnnotations;

namespace SistemaDocumentoNetCore.Models
{
    public class Documento
    {
        [Key]
        public int DocumentoId { get; set; }

        [Required(ErrorMessage ="Insira o Campo Código!")]
        [Display(Name ="Código")]       
        public int Codigo { get; set; }

        [Required(ErrorMessage ="Insira o Campo Título!")]
        [Display(Name ="Título")]
        [MaxLength(200)]
        public string? Titulo { get; set; }

        [Required(ErrorMessage = "Insira o Campo Processo!")]
        [MaxLength(200)]
        public string? Processo { get; set; }

        [Required(ErrorMessage = "Insira o Campo Categoria!")]
        [MaxLength(200)]
        public string? Categoria { get; set; }

        [Required(ErrorMessage = "Insira o Arquivo!")]
        public string? Arquivo { get; set; }
    }
}

SistemaDocumentoNetCore/Models/ErrorViewModel.cs
namespace SistemaDocumentoNetCore.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SistemaDocumentoNetCore/Controllers/DocumentoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SistemaDocumentoNetCore.AppData;
using SistemaDocumentoNetCore.Models;

namespace SistemaDocumentoNetCore.Controllers
{
    public class DocumentoController : Controller
    {
        private readonly AppDbContext _context;

        public DocumentoController(AppDbContext context)
        {
            _context = context;
        }        
        

        // GET: Documento
        public async Task<IActionResult> Index()
        {
              return _context.Documentos != null ? 
                          View(await _context.Documentos.ToListAsync()) :
                          Problem("Entity set 'AppDbContext.Documentos'  is null.");
        }

        // GET: Documento/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Documentos == null)
            {
                return NotFound();
            }

            var documento = await _context.Documentos
                .FirstOrDefaultAsync(m => m.DocumentoId == id);
            if (documento == null)
            {
                return NotFound();
            }

            return View(documento);
        }


        // GET: Documento/Create
        public IActionResult Create()
        {            
            return View();
        }

        // POST: Documento/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DocumentoId,Codigo,Titulo,Processo,Categoria,Arquivo")] Documento documento)
        {
            if (ModelState.IsValid)
            {
                _context.Add(documento);
                await _context.SaveChangesAsync();
                TempData["MensagemAlerta"] = "Documento Inserido com Sucesso!";
                return RedirectToAction(nameof(Index));
            }
            return View(documento);
        }

        // GET: Documento/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Documentos == null)
            {
                return NotFound();
            }

            var documento = await _context.Documentos.FindAsync(id);
            if (documento == null)
            {
                return NotFound();
            }
            return View(documento);
        }

        // POST: Documento/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("DocumentoId,Codigo,Titulo,Processo,Categoria,Arquivo")] Documento documento)
        {
            if (id != documento.DocumentoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(documento);
                    await _context.SaveChangesAsync();
                    TempData["MensagemAlerta"] = "Documento Editado com Sucesso!";
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DocumentoExists(documento.DocumentoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(documento);
        }

        // GET: Documento/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Documentos == null)
            {
                return NotFound();
            }

            var documento = await _context.Documentos
                .FirstOrDefaultAsync(m => m.DocumentoId == id);
            if (documento == null)
            {
                return NotFound();
            }

            return View(documento);
        }

        // POST: Documento/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Documentos == null)
            {
                return Problem("Entity set 'AppDbContext.Documentos'  is null.");
            }
            var documento = await _context.Documentos.FindAsync(id);
            if (documento != null)
            {
                _context.Documentos.Remove(documento);
            }
            
            await _context.SaveChangesAsync();
            TempData["MensagemAlerta"] = "Documento Excluido com Sucesso!";
            return RedirectToAction(nameof(Index));
        }

        private bool DocumentoExists(int id)
        {
          return (_context.Documentos?.Any(e => e.DocumentoId == id)).GetValueOrDefault();
        }
    }
}

SistemaDocumentoNetCore/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SistemaDocumentoNetCore.Models;
using System.Diagnostics;

namespace SistemaDocumentoNetCore.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SistemaDocumentoNetCore/Views/Documento/Create.cshtml
@model SistemaDocumentoNetCore.Models.Documento

@{
    ViewData["Title"] = "Inserir Documento";
}

<h4>Insira um Documento</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Codigo" class="control-label"></label>
                <input asp-for="Codigo" onkeypress="return apenasNumeros(event);" class="form-control" />
                <span asp-validation-for="Codigo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Processo" class="control-label"></label>
                <select name="Processo" id="Processo" asp-for="Processo" class="form-control"></select>
                <span asp-validation-for="Processo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Categoria" class="control-label"></label>
                <input asp-for="Categoria" class="form-control" />
                <span asp-validation-for="Categoria" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Arquivo" class="control-label"></label>
                <input type="file" asp-for="Arquivo" multiple class="form-control" />
                <span asp-validation-for="Arquivo" class="text-danger"></span>
            </div>
            <br>
            <div class="form-group">
                <input type="submit" value="Cadastrar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-link">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<script>
    function apenasNumeros(evt)
    {
        // Apenas números
        if (window.event) { 
        var charCode = evt.keyCode;
        } else if (evt.which) { 
        var charCode = evt.which
        }

        if (charCode > 31 && (charCode < 48 || charCode > 57)) {
        return false;
        }
        return true;
        }

</script>

SistemaDocumentoNetCore/Views/Documento/Delete.cshtml
@model SistemaDocumentoNetCore.Models.Documento

@{
    ViewData["Title"] = "Delete";
}

<h3>Deseja realmente excluir este documento?</h3>
<div>
    <h4>Excluir Documento</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Codigo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Codigo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Processo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Processo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Categoria)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Categoria)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Arquivo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Arquivo)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="DocumentoId" />
        <input type="submit" value="Excluir" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-link">Voltar</a>
    </form>
</div>

SistemaDocumentoNetCore/Views/Documento/Details.cshtml
@model SistemaDocumentoNetCore.Models.Documento

@{
    ViewData["Title"] = "Detalhes do Documento";
}

<div>
    <h4>Detalhes do Documento</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Codigo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Codigo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Processo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Processo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Categoria)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Categoria)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Arquivo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Arquivo)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.DocumentoId" class="btn btn-warning">Editar</a> |
    <a asp-action="Index" class="btn btn-link">Voltar</a>
</div>

SistemaDocumentoNetCore/Views/Documento/Edit.cshtml
@model SistemaDocumentoNetCore.Models.Documento

@{
    ViewData["Title"] = "Editar Documento";
}

<h4>Editar Documento</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="DocumentoId" />
            <div class="form-group">
                <label asp-for="Codigo" class="control-label"></label>
                <input asp-for="Codigo" class="form-control" />
                <span asp-validation-for="Codigo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Processo" class="control-label"></label>
                <input asp-for="Processo" class="form-control" />
                <span asp-validation-for="Processo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Categoria" class="control-label"></label>
                <input asp-for="Categoria" class="form-control" />
                <span asp-validation-for="Categoria" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Arquivo" class="control-label"></label>
                <input type="file" asp-for="Arquivo" class="form-control" />
                <span asp-validation-for="Arquivo" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-link">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SistemaDocumentoNetCore/Views/Documento/Index.cshtml
@model IEnumerable<SistemaDocumentoNetCore.Models.Documento>

@{
    ViewData["Title"] = "Index";
}

<p>
    <a asp-action="Create" class="btn btn-primary">Insira um Novo Documento</a>
</p>    

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Codigo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Titulo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Processo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Categoria)
            </th>
            <th class="disable">
                @Html.DisplayNameFor(model => model.Arquivo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Codigo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Titulo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Processo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Categoria)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Arquivo)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.DocumentoId" class="btn btn-warning">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.DocumentoId" class="btn btn-success">Detalhes</a> |
                <a asp-action="Delete" asp-route-id="@item.DocumentoId" class="btn btn-danger">Excluir</a>
            </td>
        </tr>
}
    </tbody>
</table>

SistemaDocumentoNetCore/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Sistema Documentos 1.0</h1>
    <img src="~/image/document.gif" />
</div>

SistemaDocumentoNetCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SistemaDocumentoNetCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SistemaDocumentoNetCore.styles.css" asp-append-version="true" />       
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand">Sistema Documento 1.0</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Documento" asp-action="Index">Documentos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Sebastião Trindade 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>